### ISSUE TITLE
Altering spells status effects in the UK translation does not work

### ISSUE THREAD

**Issue by BaconCatBug** [Tirlititi/Hades-Workshop#1]
When you change a spells status then save the mod while working on the UK Steam version, reloading the mod at a later date breaks every single spells status effect and breaks the status set list.

Steps to reproduce:
Load UK Steam version into HW.
Change a spells status (For example, Comet does Freeze at 40% accuracy).
Save mod.
Close HW.
Load UK Steam version into HW.
Load Mod.
All spells now have All statuses and all status sets are changed.

https://i.sli.mg/vm3wbv.png

**Comment by Tirlititi** [comment]
Found the problem. There is a little difference in the text formatting between the different languages of the Steam files.
The bug is fixed for the next version, but the .hws files created with the current one are corrupted (it doesn't concern the US version but it concerns more than the UK version ; I didn't precisely check which versions were involved).

Thanks again for pointing this.
